<a href="https://colab.research.google.com/github/data-space/datalab-notebooks/blob/master/Python/9.%20Temporary/Credit_approval_Oct8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classes & Objects - Credit Approval Dataset

The credit approval dataset is read by the `get_initial_pdf` function. 

In [0]:
import pandas as pd
def get_initial_pdf():
  pdf = pd.read_csv('https://raw.githubusercontent.com/datalab-datasets/credit-approval/master/crx.data',
                    header=None,
                    names=[f'col_{col_num}' for col_num in range(16)],
                    dtype={f'col_{num}': 'float' for num in [1,2,7,13,14]},
                    na_values=['?']
                    ) \
          .replace(to_replace={'col_15': {'+':1.0, '-':0.0}}) 
  return pdf

It is stored in the `initial_pdf` variable. We will use this later. 

In [0]:
initial_pdf = get_initial_pdf()
float_pdf   = initial_pdf.select_dtypes(include='float')
object_pdf  = initial_pdf.select_dtypes(include='object')

For reasons that will make more sense later, the dataset is split into two pieces: 
- the `float` columns are in `float_pdf` 
- the `object` columns are in `object_pdf`.

## Classes and objects
- init, get and set methods

In [0]:
class Person: 
  def __init__(self,name=''):
    self.name=name

In [0]:
host = Person(name="David")
brother = Person(name='John')

In [5]:
host.name, brother.name

('David', 'John')

In [0]:
class Person: 
  def __init__(self,name=''):
    self.name=name
  def get_name(self):
    return self.name

In [0]:
host = Person('david')

In [8]:
host.get_name()

'david'

In [0]:
class Person: 
  def __init__(self,name=''):
    self.name=name
  def get_name(self):
    return self.name
  def set_name(self,name):
    self.name=name
    return self

In [0]:
host = Person()

In [11]:
host.get_name()

''

In [12]:
host.set_name('David')

In [13]:
host.get_name()

'David'

In [14]:
host.set_name('Davie').get_name()

'Davie'

From this section remember:
- The "init" method records the initial parameters used when creating the object
- The "get" method return values from the object
- The "set" method stores values in the object and returns `self` (the object)


## Transformer classes and objects

### `DoNothing` class (first example)

In [0]:
from sklearn.base import BaseEstimator, TransformerMixin
class DoNothing(BaseEstimator, TransformerMixin):
  def __init__(self):
    return
  def fit(self, X, y=None):
    return self
  def transform(self, X):
    return X

In [0]:
no_op = DoNothing()

In [17]:
no_op.fit(initial_pdf)

DoNothing()

In [0]:
transformed_pdf = no_op.transform(initial_pdf)

In [19]:
transformed_pdf.equals(initial_pdf)

True

### `DataFrameSelector` class (second example)

In [0]:
class DataFrameSelector(BaseEstimator, TransformerMixin):
  def __init__(self, attribute_names=[]):
    self.attribute_names = attribute_names
  def fit(self, X, y=None):
    return self
  def transform(self, X):
    return X[self.attribute_names]

In [21]:
(DataFrameSelector(attribute_names=['col_1','col_2'])
.fit(float_pdf)
.transform(float_pdf)
.head()
)

col_1  col_2
0  30.83  0.000
1  58.67  4.460
2  24.50  0.500
3  27.83  1.540
4  20.17  5.625

## Transforming `object` columns 

### `Object` - `SimpleImputer`

In [0]:
from sklearn.impute import SimpleImputer
import numpy as np

In [0]:
imp = SimpleImputer(missing_values=np.nan,
                    strategy='most_frequent')

In [24]:
imp.fit(object_pdf)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [25]:
imp.statistics_

array(['b', 'u', 'g', 'c', 'v', 't', 'f', 'f', 'g'], dtype=object)

In [26]:
object_pdf.columns

Index(['col_0', 'col_3', 'col_4', 'col_5', 'col_6', 'col_8', 'col_9', 'col_11',
       'col_12'],
      dtype='object')

In [27]:
object_pdf.col_0.value_counts()

b    468
a    210
Name: col_0, dtype: int64

In [28]:
object_pdf.col_3.value_counts()

u    519
y    163
l      2
Name: col_3, dtype: int64

In [0]:
imputed_object_arr = imp.transform(object_pdf)

In [30]:
imputed_object_arr

array([['b', 'u', 'g', ..., 't', 'f', 'g'],
       ['a', 'u', 'g', ..., 't', 'f', 'g'],
       ['a', 'u', 'g', ..., 'f', 'f', 'g'],
       ...,
       ['a', 'y', 'p', ..., 't', 't', 'g'],
       ['b', 'u', 'g', ..., 'f', 'f', 'g'],
       ['b', 'u', 'g', ..., 'f', 't', 'g']], dtype=object)

### `Object` - `OneHotEncoder`

- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [0]:
from sklearn.preprocessing import OneHotEncoder

In [0]:
ohe = OneHotEncoder()

In [33]:
test_arr = imputed_object_arr[5:15,:3]
test_arr

array([['b', 'u', 'g'],
       ['b', 'u', 'g'],
       ['a', 'u', 'g'],
       ['b', 'y', 'p'],
       ['b', 'y', 'p'],
       ['b', 'u', 'g'],
       ['b', 'u', 'g'],
       ['a', 'u', 'g'],
       ['b', 'u', 'g'],
       ['a', 'u', 'g']], dtype=object)

In [34]:
ohe.fit(test_arr).transform(test_arr).todense()

matrix([[0., 1., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1.],
        [0., 1., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0.]])

In [0]:
ohe_imputed_object_pdf = ohe.fit(imputed_object_arr).transform(imputed_object_arr)

In [36]:
ohe_imputed_object_pdf.todense()

matrix([[0., 1., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        ...,
        [1., 0., 0., ..., 1., 0., 0.],
        [0., 1., 0., ..., 1., 0., 0.],
        [0., 1., 0., ..., 1., 0., 0.]])

## `Float`

### `Float` - `SimpleImputer`

- https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

In [0]:
from sklearn.impute import SimpleImputer
import numpy as np

In [0]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [39]:
imp.fit(float_pdf)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [0]:
imputed_float_pdf = imp.transform(float_pdf)

### `Float` - `MinMaxScaler`

In [0]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [42]:
scaler.fit(imputed_float_pdf)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [43]:
scaler.data_min_, scaler.data_max_

(array([13.75,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]),
 array([8.025e+01, 2.800e+01, 2.850e+01, 2.000e+03, 1.000e+05, 1.000e+00]))

In [0]:
scaled_imputed_float_pdf = scaler.transform(imputed_float_pdf)

In [45]:
(scaled_imputed_float_pdf.min(), 
 scaled_imputed_float_pdf.max()
 )

(0.0, 1.0)

## `Object` - `Pipeline`

In [0]:
imp = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputed_object_arr =  imp.fit(object_pdf).transform(object_pdf)

In [0]:
ohe = OneHotEncoder()
ohe_imputed_object_arr = ohe.fit(imputed_object_arr).transform(imputed_object_arr)

In [48]:
ohe_imputed_object_arr.todense()

matrix([[0., 1., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        ...,
        [1., 0., 0., ..., 1., 0., 0.],
        [0., 1., 0., ..., 1., 0., 0.],
        [0., 1., 0., ..., 1., 0., 0.]])

In [0]:
from sklearn.pipeline import Pipeline
imp_ohe_pipe = Pipeline(steps=[('imp_obj', SimpleImputer(missing_values=np.nan,strategy='most_frequent')),
                               ('ohe_obj', OneHotEncoder())
                               ]
)              

In [50]:
pipe_ohe_imputed_object_arr = imp_ohe_pipe.fit(object_pdf).transform(object_pdf)
np.array_equal(pipe_ohe_imputed_object_arr.todense(),
                    ohe_imputed_object_arr.todense()
               )

True

## `Float` - `Pipeline`

In [0]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imputed_float_arr = imp.fit(float_pdf).transform(float_pdf)

In [0]:
scaler = MinMaxScaler()
scaled_imputed_float_arr = scaler.fit(imputed_float_arr).transform(imputed_float_arr)

In [0]:
from sklearn.pipeline import Pipeline
imp_sca_pipe = Pipeline(steps=[('imp_flt', SimpleImputer(missing_values=np.nan,strategy='mean')),
                               ('sca_flt', MinMaxScaler())
                               ]
)              

In [0]:
pipe_scaled_imputed_float_arr = imp_sca_pipe.fit(float_pdf).transform(float_pdf)

In [55]:
np.array_equal(pipe_scaled_imputed_float_arr,
               scaled_imputed_float_arr)

True

## `FeatureUnion`

In [0]:
from sklearn.pipeline import FeatureUnion

In [0]:
class SelectDtypePDF(BaseEstimator, TransformerMixin):
  def __init__(self, dtype=[]):
    self.dtype = dtype
  def fit(self, X, y=None):
    return self
  def transform(self, X):
    return X.select_dtypes(self.dtype)

In [58]:
SelectDtypePDF(dtype='float').fit(initial_pdf).transform(initial_pdf).head()

col_1  col_2  col_7  col_13  col_14  col_15
0  30.83  0.000   1.25   202.0     0.0     1.0
1  58.67  4.460   3.04    43.0   560.0     1.0
2  24.50  0.500   1.50   280.0   824.0     1.0
3  27.83  1.540   3.75   100.0     3.0     1.0
4  20.17  5.625   1.71   120.0     0.0     1.0

In [59]:
float_pdf.columns

Index(['col_1', 'col_2', 'col_7', 'col_13', 'col_14', 'col_15'], dtype='object')

In [0]:
from sklearn.pipeline import Pipeline
sel_imp_sca_pipe = Pipeline(steps=[('sel_flt', SelectDtypePDF('float')),
                                   ('imp_flt', SimpleImputer(missing_values=np.nan,strategy='mean')),
                                   ('sca_flt', MinMaxScaler())])              

In [61]:
np.array_equal(sel_imp_sca_pipe.fit(initial_pdf).transform(initial_pdf),
                   imp_sca_pipe.fit(float_pdf)  .transform(float_pdf))

True

In [0]:
from sklearn.pipeline import Pipeline
sel_imp_ohe_pipe = Pipeline(steps=[('sel_obj', SelectDtypePDF('object')),
                                   ('imp_obj', SimpleImputer(missing_values=np.nan,strategy='most_frequent')),
                                   ('ohe_obj', OneHotEncoder())
                               ])              

In [63]:
np.array_equal(imp_ohe_pipe.fit(object_pdf).transform(object_pdf).todense(),
               sel_imp_ohe_pipe.fit(initial_pdf).transform(initial_pdf).todense()
               )

True

In [0]:
float_object_fea_un = FeatureUnion(transformer_list=[('flt',sel_imp_sca_pipe),
                                                    ('obj',sel_imp_ohe_pipe)])

In [0]:
fea_un_arr = float_object_fea_un.fit(initial_pdf).transform(initial_pdf)

In [0]:
concat_flt_obj_arr = \
np.concatenate((sel_imp_ohe_pipe.fit(initial_pdf).transform(initial_pdf).todense(),
                sel_imp_sca_pipe.fit(initial_pdf).transform(initial_pdf)),
               axis=1)

In [67]:
np.array_equal(fea_un_arr.shape, concat_flt_obj_arr.shape)

True

In [0]:
float_object_fea_un = \
FeatureUnion(
    transformer_list=[('flt',Pipeline(steps=[('sel_flt', SelectDtypePDF('float')),
                                             ('imp_flt', SimpleImputer(missing_values=np.nan,strategy='mean')),
                                             ('sca_flt', MinMaxScaler())])),
                      ('obj',Pipeline(steps=[('sel_obj', SelectDtypePDF('object')),
                                             ('imp_obj', SimpleImputer(missing_values=np.nan,strategy='most_frequent')),
                                             ('ohe_obj', OneHotEncoder())]))])

In [69]:
float_object_fea_un.fit(initial_pdf).transform(initial_pdf)

<690x46 sparse matrix of type '<class 'numpy.float64'>'
	with 9450 stored elements in Compressed Sparse Row format>