<a href="https://colab.research.google.com/github/data-space/datalab-notebooks/blob/master/Python/9.%20Temporary/Workshop_Scikit_learn_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scikit-learn Workshop - 19 Nov 2019

## Setup

In [0]:
import pandas  as pd
import numpy   as np
import sklearn as sk

### Iris dataset

In [0]:
import pandas as pd
from sklearn.datasets import load_iris
iris_features = load_iris().data[:, 1:]
iris_target   = load_iris().data[:,:1]

### Diamonds dataset

In [71]:
import pandas as pd
diamonds_pdf = pd.read_csv('https://raw.githubusercontent.com/datalab-datasets/file-samples/master/diamonds.csv').drop(columns='Unnamed: 0')
diamonds_pdf.columns
diamonds_features = diamonds_pdf.drop(labels='price',axis=1)[['x','y','z']] #select_dtypes(include=['float','int'])
diamonds_target = diamonds_pdf['price']
diamonds_features

x     y     z
0      3.95  3.98  2.43
1      3.89  3.84  2.31
2      4.05  4.07  2.31
3      4.20  4.23  2.63
4      4.34  4.35  2.75
...     ...   ...   ...
53935  5.75  5.76  3.50
53936  5.69  5.75  3.61
53937  5.66  5.68  3.56
53938  6.15  6.12  3.74
53939  5.83  5.87  3.64

[53940 rows x 3 columns]

In [0]:
def get_boston_housing_pdf(): # for boston housing dataset
  from sklearn.datasets import load_boston
  feature_names = [name.lower() 
                   for name in load_boston().get('feature_names').tolist()
                  ]
  features_pdf = pd.DataFrame(data=load_boston().get('data'),
                              columns=feature_names
                             )
  target_pdf = pd.DataFrame(data={'price': load_boston().get('target')}
                           )
  return pd.concat([features_pdf, target_pdf],
                   axis='columns',
                   join='inner')

In [60]:
boston_housing_pdf = get_boston_housing_pdf().select_dtypes(include=['float','int'])

boston_housing_features = boston_housing_pdf.drop(labels='price',axis=1)
boston_housing_target = boston_housing_pdf['price']
boston_housing_features

crim    zn  indus  chas    nox  ...  rad    tax  ptratio       b  lstat
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

Our first step is to create a train dataset and a test dataset from our dataset, which is `iris_features` and `iris_target`. Use the `train_test_split` function from the `sklearn` library to do so. 

In [0]:
from sklearn.model_selection import train_test_split
iris_x_train, iris_x_test, iris_y_train, iris_y_test = train_test_split(iris_features,
                                                    iris_target)

Notice that the train dataset is `iris_x_train` and `iris_y_train`, which correspond to the features and the target. 

__Exercise__: create train and test datasets 
- for the `diamonds_features`, `diamonds_target` dataset called `diamonds_x_train`, `diamonds_x_test`, `diamonds_y_train`, `diamonds_y_test`
- for the `boston_housing_features`,`boston_housing_target` dataset called `boston_x_train`, `boston_x_test`, `boston_y_train`, `boston_y_test`

In both cases put the result of the 

## Algorithms to models to predictions and scores

Linear regression is an algorithm. This algorithm (and many others) have parameters that determine how they work. The Scikit-learn version of the linear regression algorithm has parameters named `copy_X`, `fit_intercept`, `n_jobs`, `normalize`. The values indicated below are defaults. 

In [62]:
from sklearn.linear_model import LinearRegression
iris_linreg_algorithm = LinearRegression()
iris_linreg_algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

__Exercise__: Create algorithm objects for diamonds and boston, named `diamonds_linreg_algorithm` and `boston_linreg_algorithm`.

Recall that algorithms take train datasets as input and produce models as output. We do this for the iris dataset below, using the `fit` method of the .

In [63]:
iris_linreg_model = iris_linreg_algorithm.fit(X=iris_x_train,
                                              y=iris_y_train)
iris_linreg_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

__Exercise__: Create model objects for diamonds and boston, named `diamonds_linreg_model` and `boston_linreg_model`. Use the corresponding train dataset.

Recall that models take test datasets as input and produce predictions as output. We do this for the iris dataset below, using the `predict` method.

In [64]:
iris_linreg_predictions = iris_linreg_model.predict(X=iris_x_train)
iris_linreg_predictions

array([[6.66716079],
       [4.82551457],
       [5.28013658],
       [5.87978661],
       [6.30379665],
       [5.75592254],
       [6.21530277],
       [6.39016848],
       [5.09022195],
       [5.74981203],
       [6.3814218 ],
       [5.01053865],
       [4.72203568],
       [4.88403842],
       [6.33376668],
       [4.89284901],
       [5.30457412],
       [6.70124711],
       [5.51365848],
       [5.38078307],
       [6.86389179],
       [6.2867535 ],
       [6.0438475 ],
       [6.72304848],
       [6.34321921],
       [6.19285946],
       [5.45017565],
       [6.00300874],
       [7.09117084],
       [6.31878167],
       [7.20764052],
       [6.06905931],
       [5.16167267],
       [6.65095582],
       [6.171122  ],
       [5.45635007],
       [5.16167267],
       [5.02963995],
       [5.393068  ],
       [5.15961453],
       [5.70151497],
       [7.36694319],
       [4.81052956],
       [6.19961191],
       [4.79554454],
       [4.67849684],
       [6.68420395],
       [5.678

__Exercise__: Create predictions for diamonds and for boston named `diamonds_linreg_predictions` and `boston_linreg_predictions`.

In [65]:
iris_linreg_model.score(X=iris_x_test,
                        y=iris_y_test)

0.8425650881482449

__Exercise__: Create a score for the predictions for diamonds and for boston named `diamonds_linreg_score` and `boston_linreg_score`.

## Try other algorithms

In [66]:
from sklearn.tree import DecisionTreeRegressor
iris_decisiontree_algorithm = DecisionTreeRegressor()
iris_decisiontree_model = iris_decisiontree_algorithm.fit(X=iris_x_train,
                                                          y=iris_y_train)
iris_decisiontree_predictions = iris_decisiontree_model.predict(X=iris_x_test)
iris_decisiontree_predictions

array([5.5 , 5.5 , 5.  , 5.1 , 6.  , 5.1 , 5.8 , 4.6 , 6.7 , 4.6 , 5.  ,
       4.9 , 5.  , 7.4 , 5.5 , 6.4 , 5.  , 6.4 , 5.8 , 5.8 , 6.7 , 6.5 ,
       6.5 , 5.6 , 5.  , 7.  , 5.5 , 6.4 , 5.1 , 4.55, 4.55, 6.2 , 6.7 ,
       6.7 , 5.8 , 5.4 , 6.4 , 5.5 ])

In [68]:
iris_decisiontree_score = iris_decisiontree_model.score(X=iris_x_test,
                                                        y=iris_y_test)
iris_decisiontree_score

0.7173334297037813

__Exercise__: Create an algorithm, model, predictions and score (based on the decision tree algorithm) for diamonds and for boston.

In [69]:
from sklearn.neighbors import KNeighborsRegressor
iris_kneighbors_algorithm = KNeighborsRegressor()
iris_kneighbors_model = iris_kneighbors_algorithm.fit(X=iris_x_train,
                                                          y=iris_y_train)
iris_kneighbors_predictions = iris_kneighbors_model.predict(X=iris_x_test)
iris_kneighbors_predictions

array([[5.62],
       [5.66],
       [4.78],
       [4.96],
       [6.22],
       [5.  ],
       [6.12],
       [4.92],
       [6.72],
       [4.76],
       [4.86],
       [4.64],
       [4.68],
       [7.4 ],
       [5.5 ],
       [6.  ],
       [5.02],
       [6.34],
       [6.02],
       [6.12],
       [6.54],
       [6.9 ],
       [6.5 ],
       [5.8 ],
       [4.92],
       [6.6 ],
       [5.58],
       [6.44],
       [4.94],
       [4.92],
       [4.92],
       [6.04],
       [6.38],
       [6.34],
       [6.04],
       [5.3 ],
       [6.56],
       [6.04]])

In [70]:
iris_kneighbors_score = iris_kneighbors_model.score(X=iris_x_test,
                                                        y=iris_y_test)
iris_kneighbors_score

0.8123917940563528

__Exercise__: Create an algorithm, model, predictions and score (based on the k-nearest neighbor algorithm) for boston.