<a href="https://colab.research.google.com/github/data-space/datalab-notebooks/blob/master/Python/9.%20Temporary/Workshop_Scikit_learn_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scikit-learn Workshop - 19 Nov 2019

## Setup

In [0]:
import pandas  as pd
import numpy   as np
import sklearn as sk

### Iris dataset

In [0]:
import pandas as pd
from sklearn.datasets import load_iris
iris_features = load_iris().data[:,1:]
iris_target   = load_iris().data[:,:1]

### Diamonds dataset

In [3]:
import pandas as pd
diamonds_pdf = pd.read_csv('https://raw.githubusercontent.com/datalab-datasets/file-samples/master/diamonds.csv').drop(columns='Unnamed: 0')
diamonds_pdf.columns
diamonds_features = diamonds_pdf.drop(labels='price',axis=1)[['x','y','z']]
diamonds_target = diamonds_pdf['price']
diamonds_features.head()

x     y     z
0  3.95  3.98  2.43
1  3.89  3.84  2.31
2  4.05  4.07  2.31
3  4.20  4.23  2.63
4  4.34  4.35  2.75

In [0]:
def get_boston_housing_pdf(): # for boston housing dataset
  from sklearn.datasets import load_boston
  feature_names = [name.lower() 
                   for name in load_boston().get('feature_names').tolist()
                  ]
  features_pdf = pd.DataFrame(data=load_boston().get('data'),
                              columns=feature_names
                             )
  target_pdf = pd.DataFrame(data={'price': load_boston().get('target')}
                           )
  return pd.concat([features_pdf, target_pdf],
                   axis='columns',
                   join='inner')

In [5]:
boston_housing_pdf = get_boston_housing_pdf().select_dtypes(include=['float','int'])

boston_housing_features = boston_housing_pdf.drop(labels='price',axis=1)
boston_housing_target = boston_housing_pdf['price']
boston_housing_features.head()

crim    zn  indus  chas    nox  ...  rad    tax  ptratio       b  lstat
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

Our first step is to create a train dataset and a test dataset from our dataset, which is `iris_features` and `iris_target`. Use the `train_test_split` function from the `sklearn` library to do so. 

In [0]:
from sklearn.model_selection import train_test_split
iris_x_train, iris_x_test, iris_y_train, iris_y_test = train_test_split(iris_features,
                                                                        iris_target)

Notice that the train dataset is `iris_x_train` and `iris_y_train`, which correspond to the features and the target. 

__Exercise__: create train and test datasets 
- for the `diamonds_features`, `diamonds_target` dataset called `diamonds_x_train`, `diamonds_x_test`, `diamonds_y_train`, `diamonds_y_test`
- for the `boston_housing_features`,`boston_housing_target` dataset called `boston_x_train`, `boston_x_test`, `boston_y_train`, `boston_y_test`

In both cases put the result of the 

## Algorithms to models to prediction

Linear regression is an algorithm. This algorithm (and many others) have parameters that determine how they work. The Scikit-learn version of the linear regression algorithm has parameters named `copy_X`, `fit_intercept`, `n_jobs`, `normalize`. The values indicated below are defaults. 

In [7]:
from sklearn.linear_model import LinearRegression
iris_linreg_algorithm = LinearRegression()
iris_linreg_algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

__Exercise__: Create algorithm objects for diamonds and boston, named `diamonds_linreg_algorithm` and `boston_linreg_algorithm`.

Recall that algorithms take train datasets as input and produce models as output. We do this for the iris dataset below, using the `fit` method of the .

In [8]:
iris_linreg_model = iris_linreg_algorithm.fit(X=iris_x_train,
                                              y=iris_y_train)
iris_linreg_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

__Exercise__: Create model objects for diamonds and boston, named `diamonds_linreg_model` and `boston_linreg_model`. Use the corresponding train dataset.

Recall that models take test datasets as input and produce predictions as output. We do this for the iris dataset below, using the `predict` method.

In [9]:
iris_linreg_predictions = iris_linreg_model.predict(X=iris_x_train)
iris_linreg_predictions

array([[6.27836621],
       [5.72172849],
       [6.47944588],
       [4.98139783],
       [6.55285333],
       [6.43774758],
       [5.19840125],
       [5.71394093],
       [5.97960887],
       [6.31046535],
       [6.56937735],
       [5.09736629],
       [6.20500012],
       [7.31160233],
       [4.99585862],
       [5.46699513],
       [4.78600113],
       [4.60777008],
       [5.96850538],
       [4.79185301],
       [6.86568146],
       [4.65682459],
       [7.8716387 ],
       [6.27690324],
       [6.15740858],
       [4.87782692],
       [6.3949763 ],
       [5.19840125],
       [5.16986968],
       [5.91945087],
       [4.94534114],
       [4.7058791 ],
       [6.50083152],
       [5.06337283],
       [4.72287583],
       [6.70147983],
       [6.55139036],
       [7.76281617],
       [6.46102754],
       [5.51768153],
       [6.74472383],
       [6.17251099],
       [7.1843201 ],
       [6.24634979],
       [4.79331598],
       [7.1799312 ],
       [6.36287715],
       [6.292

__Exercise__: Create predictions for diamonds and for boston named `diamonds_linreg_predictions` and `boston_linreg_predictions`.

In [10]:
iris_linreg_model.score(X=iris_x_test,
                        y=iris_y_test)

0.8707089962340753

__Exercise__: Create a score for the predictions for diamonds and for boston named `diamonds_linreg_score` and `boston_linreg_score`.

## Try other algorithms

Below we try the decision tree and k-nearest neighbor algorithms on the same datasets. 

### Decision tree

Below we swap in the decision tree algorithm at the beginning of the sequence. Notice though that the remaining steps are the same. 

In [11]:
from sklearn.tree import DecisionTreeRegressor
iris_decisiontree_algorithm = DecisionTreeRegressor()
iris_decisiontree_algorithm

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [12]:
iris_decisiontree_model = iris_decisiontree_algorithm.fit(X=iris_x_train,
                                                          y=iris_y_train)
iris_decisiontree_model

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [13]:
iris_decisiontree_score = iris_decisiontree_model.score(X=iris_x_test,
                                                        y=iris_y_test)
iris_decisiontree_score

0.7839381380774286

In [14]:
iris_decisiontree_predictions = iris_decisiontree_model.predict(X=iris_x_test)
iris_decisiontree_predictions

array([4.9 , 6.8 , 5.7 , 7.7 , 4.6 , 4.55, 5.1 , 4.6 , 4.9 , 7.9 , 5.  ,
       5.5 , 5.1 , 6.1 , 6.5 , 4.6 , 5.5 , 5.6 , 6.7 , 6.2 , 4.8 , 4.55,
       6.1 , 5.5 , 6.  , 5.5 , 6.1 , 5.8 , 5.6 , 6.1 , 6.2 , 4.55, 4.55,
       4.9 , 5.8 , 4.55, 6.7 , 5.7 ])

Below the steps are run in a single code cell. 

In [15]:
from sklearn.tree import DecisionTreeRegressor
iris_decisiontree_algorithm   = DecisionTreeRegressor()
iris_decisiontree_model       = iris_decisiontree_algorithm.fit(X=iris_x_train,
                                                                y=iris_y_train)
iris_decisiontree_score       = iris_decisiontree_model.score(X=iris_x_test,
                                                              y=iris_y_test)
iris_decisiontree_predictions = iris_decisiontree_model.predict(X=iris_x_test)

(iris_decisiontree_score, 
 iris_decisiontree_predictions
)

(0.7884194211395262,
 array([4.9 , 6.8 , 5.7 , 7.7 , 4.6 , 4.55, 5.1 , 4.6 , 4.9 , 7.7 , 5.  ,
        5.6 , 5.1 , 6.1 , 6.5 , 4.6 , 5.6 , 5.6 , 7.  , 6.2 , 4.8 , 4.6 ,
        6.1 , 5.5 , 6.  , 5.5 , 6.1 , 5.8 , 5.6 , 6.1 , 6.2 , 4.55, 4.55,
        5.1 , 5.8 , 4.6 , 6.7 , 5.7 ]))

__Exercise__: copy-paste the above code cell and modify the copy to work with the diamonds dataset. They modify another copy to work with the boston dataset.  

### K-nearest neighbors

See the documentation and modify the below code cell to work with the 

- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#sklearn.neighbors.KNeighborsRegressor

In [0]:
from sklearn.tree import DecisionTreeRegressor
iris_decisiontree_algorithm   = DecisionTreeRegressor()
iris_decisiontree_model       = iris_decisiontree_algorithm.fit(X=iris_x_train,
                                                                y=iris_y_train)
iris_decisiontree_score       = iris_decisiontree_model.score(X=iris_x_test,
                                                              y=iris_y_test)
iris_decisiontree_predictions = iris_decisiontree_model.predict(X=iris_x_test)

(iris_decisiontree_score, 
 iris_decisiontree_predictions
)