# Essentials - Matrices

![alt](http://www.scatter.com/images/DataLab_logo.jpg)

## Table Of Contents
1. What are matrices?
2. Functions on matrices
3. Selection of elements in matrices
4. Arithmetic operations on matrices

## What are matrices? 

Matrices are two dimensional arrays in R. What makes them different from dataframes are that all the columns of a matrix have to be of the same data type, which wasn't the case with dataframes. In Dataframes, elements within a column have to be of the same data type, but different columns can be of different data types.

Matrices can be constructed using the "`matrix()`" command.

In [6]:
%r
my_matrix <- matrix(1:9, byrow=TRUE, nrow=3)
my_matrix

[,1] [,2] [,3]
[1,] 1 2 3
[2,] 4 5 6
[3,] 7 8 9

In [7]:
%r
?matrix

matrix package:base R Documentation

Matrices

Description:

 ‘matrix’ creates a matrix from the given set of values.

 ‘as.matrix’ attempts to turn its argument into a matrix.

 ‘is.matrix’ tests if its argument is a (strict) matrix.

Usage:

 matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
 dimnames = NULL)
 
 as.matrix(x, ...)
 ## S3 method for class 'data.frame'
 as.matrix(x, rownames.force = NA, ...)
 
 is.matrix(x)
 
Arguments:

 data: an optional data vector (including a list or ‘expression’
 vector). Non-atomic classed R objects are coerced by
 ‘as.vector’ and all attributes discarded.

 nrow: the desired number of rows.

 ncol: the desired number of columns.

 byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
 columns, otherwise the matrix is filled by rows.

dimnames: A ‘dimnames’ attribute for the matrix: ‘NULL’ or a ‘list’ of
 length 2 giving the row and column names respectively. An
 empty list is treated as ‘NULL’, and a list of length one as
 row names. The list can be named, and the list names will be
 used as names for the dimensions.

 x: an R object.

 ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
 character (rather than ‘NULL’) ‘rownames’. The default,
 ‘NA’, uses ‘NULL’ rownames if the data frame has ‘automatic’
 row.names or for a zero-row data frame.

Details:

 If one of ‘nrow’ or ‘ncol’ is not given, an attempt is made to
 infer it from the length of ‘data’ and the other parameter. If
 neither is given, a one-column matrix is returned.

 If there are too few elements in ‘data’ to fill the matrix, then
 the elements in ‘data’ are recycled. If ‘data’ has length zero,
 ‘NA’ of an appropriate type is used for atomic vectors (‘0’ for
 raw vectors) and ‘NULL’ for lists.

 ‘is.matrix’ returns ‘TRUE’ if ‘x’ is a vector and has a ‘"dim"’
 attribute of length 2 and ‘FALSE’ otherwise. Note that a
 ‘data.frame’ is *not* a matrix by this test. The function is
 generic: you can write methods to handle specific classes of
 objects, see InternalMethods.

 ‘as.matrix’ is a generic function. The method for data frames
 will return a character matrix if there is only atomic columns and
 any non-(numeric/logical/complex) column, applying ‘as.vector’ to
 factors and ‘format’ to other non-character columns. Otherwise,
 the usual coercion hierarchy (logical < integer < double <
 complex) will be used, e.g., all-logical data frames will be
 coerced to a logical matrix, mixed logical-integer will give a
 integer matrix, etc.

 The default method for ‘as.matrix’ calls ‘as.vector(x)’, and hence
 e.g. coerces factors to character vectors.

 When coercing a vector, it produces a one-column matrix, and
 promotes the names (if any) of the vector to the rownames of the
 matrix.

 ‘is.matrix’ is a primitive function.

 The ‘print’ method for a matrix gives a rectangular layout with
 dimnames or indices. For a list matrix, the entries of length not
 one are printed in the form ‘integer,7’ indicating the type and
 length.

Note:

 If you just want to convert a vector to a matrix, something like
 
 dim(x) <- c(nx, ny)
 dimnames(x) <- list(row_names, col_names)

 will avoid duplicating ‘x’.

References:

 Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
 Language_. Wadsworth & Brooks/Cole.

See Also:

 ‘data.matrix’, which attempts to convert to a numeric matrix.

 A matrix is the special case of a two-dimensional ‘array’.

Examples:

 is.matrix(as.matrix(1:10))
 !is.matrix(warpbreaks) # data.frame, NOT matrix!
 warpbreaks[1:10,]
 as.matrix(warpbreaks[1:10,]) # using as.matrix.data.frame(.) method
 
 ## Example of setting row and column names
 mdat <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE,
 dimnames = list(c("row1", "row2"),
 c("C.1", "C.2", "C.3")))
 mdat

Since the parameter byrow was true, the sequence of elements were filled in row wise. By default, matrices are filled in column wise. Another example can illustrate the filling up of a matrix column wise.

In [9]:
%r
my_matrix2 <- matrix(10:18,nrow=3)
my_matrix2

[,1] [,2] [,3]
[1,] 10 13 16
[2,] 11 14 17
[3,] 12 15 18

Vectors can be strung together to form a matrix.

In [11]:
%r
MondayTemp <- c(87,71)
TuesdayTemp <- c(83,69)
WednesdayTemp <- c(84,72)

Temperature <- c(MondayTemp, TuesdayTemp, WednesdayTemp )

TempMatrix <- matrix(Temperature, byrow=TRUE, nrow=3)
TempMatrix

[,1] [,2]
[1,] 87 71
[2,] 83 69
[3,] 84 72

The matrix would be more readable if the rows and columns had been named. This can be done by using the rownames() and colnames() functions.

In [13]:
%r
Days <- c("Monday", "Tuesday", "Wednesday")
Levels <- c("High","Low")

rownames(TempMatrix) <- Days
colnames(TempMatrix) <- Levels
TempMatrix

High Low
Monday 87 71
Tuesday 83 69
Wednesday 84 72

If another row had to be added to the matrix, the command we had learnt earlier in the Dataframes chapter can be used on matrices too i.e. rbind(). Similarly cbind can be used to add columns too.

### Functions on matrices

Functions such has rowSums(), colSums(), mean() can be performed on matrices.

In [17]:
%r
my_matrix <- matrix(1:9, byrow=TRUE, nrow=3)
my_matrix

[,1] [,2] [,3]
[1,] 1 2 3
[2,] 4 5 6
[3,] 7 8 9

In [18]:
%r
rowSums(my_matrix)

[1] 6 15 24

In [19]:
%r
colSums(my_matrix)

[1] 12 15 18

In [20]:
%r
mean(my_matrix)

[1] 5

As seen in the above example, the mean() function calculates the average of all the elements in the matrix. The average of rows and columns can be calculated by subsetting the matrix which can be seen in the next part.

### Selection of elements in Matrices

Similar to dataframes, square brackets __[ ]__ can be used to subset matrices.

In [24]:
%r
TempMatrix[,2]

Monday Tuesday Wednesday 
 71 69 72

In [25]:
%r
TempMatrix[1,]

High Low 
 87 71

In [26]:
%r
TempMatrix[1:2,]

High Low
Monday 87 71
Tuesday 83 69

In [27]:
%r
x1<-TempMatrix[1,]
x2<-TempMatrix[3,]
x3<-rbind(x1,x2)
x3

High Low
x1 87 71
x2 84 72

In [28]:
%r
x4<-TempMatrix[c(1,3),]
x4

High Low
Monday 87 71
Wednesday 84 72

If the average of the __high__ temperatures recorded is to be found, the following code can be used:

In [30]:
%r
mean(TempMatrix[,1])

[1] 84.66667

### Arithmetic on matrices

A number is added , subtracted, multiplied, divided with each element in a matrix.

In [33]:
%r
my_matrix*10

[,1] [,2] [,3]
[1,] 10 20 30
[2,] 40 50 60
[3,] 70 80 90

Matrix mutiplication is performed using a different operator i.e. __%*%__

In [35]:
%r
my_matrix

[,1] [,2] [,3]
[1,] 1 2 3
[2,] 4 5 6
[3,] 7 8 9

In [36]:
%r
my_matrix2

[,1] [,2] [,3]
[1,] 10 13 16
[2,] 11 14 17
[3,] 12 15 18

In [37]:
%r
my_matrix %*% my_matrix2

[,1] [,2] [,3]
[1,] 68 86 104
[2,] 167 212 257
[3,] 266 338 410

In [38]:
%r
tempm1<-matrix(1:6, byrow=TRUE, nrow=2)
tempm2<-matrix(7:12, byrow=TRUE, nrow=2)
tempm3<- tempm1 * tempm2
tempm3

[,1] [,2] [,3]
[1,] 7 16 27
[2,] 40 55 72

In [39]:
%r
tempm1<-matrix(1:6, byrow=TRUE, nrow=2)
tempm2<-matrix(7:12, nrow=3)
tempm3<- tempm1  %*% tempm2
tempm3

[,1] [,2]
[1,] 50 68
[2,] 122 167

__Exercise:__ Construct a 3x3 matrix with row and column names for the sequence 10,20,30,40,50,60,70,80,90. Let the row labels be Row_1, Row_2, Row_3 and column names be Col_1, Col_2, Col_3. Find the average of each row. Finally, divide the matrix by 5. Will it be possible to mutiply the matrix by a 1X3 matrix with the elements 1,2,3 ? Try this and find out.

__The End__