# NumPy - Matrices





- Name: Sherry TP 
- Date: Oct, 2019 
- Added Exercise Answers 

In [1]:
import numpy as np

## Matrix Arithmetic

In [2]:
X = np.array([[1,2,3],[4,5,6]])
y = np.ones((3,1))
print ("X.shape =",X.shape)
print ("y.shape =",y.shape)

X.shape = (2, 3)
y.shape = (3, 1)


In [3]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
y

array([[1.],
       [1.],
       [1.]])

In [5]:
1000 + X

array([[1001, 1002, 1003],
       [1004, 1005, 1006]])

In [6]:
10 * X

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
X + X

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
10 ** X

array([[     10,     100,    1000],
       [  10000,  100000, 1000000]])

In [9]:
y ** 10

array([[1.],
       [1.],
       [1.]])

In [10]:
X * X

array([[ 1,  4,  9],
       [16, 25, 36]])

## Matrix Functions and Methods

Matrix multiplication 

- https://www.mathsisfun.com/algebra/matrix-multiplying.html

Notice the shapes of `X` and `y` (created above.)

In [11]:
(X.shape,
 y.shape
)

((2, 3), (3, 1))

In [12]:
X = np.array([[1,2,3],[4,5,6]])
y = np.ones((3,2))
print ("X.shape =",X.shape)
print ("y.shape =",y.shape)

X.shape = (2, 3)
y.shape = (3, 2)


In [13]:
X.dot(y)

array([[ 6.,  6.],
       [15., 15.]])

__Exercises__: 
1. Take the dot product of a subset of `X` and the entire array `y` that equals `6`.
1. Take the dot product of a subset of `X` and the entire array `y` that equals `15`.
1. Take the dot product of the transpose of `y` and a subset of the transpose of `X` and that equals `6`.

Lookup the transpose function for Numpy arrays on the _Routines_ page:
- https://docs.scipy.org/doc/numpy/reference/routines.html

For each of the above items, you may want to create variables to hold the subsets or transposes. 

Your final result though should consist of a single line of code (for each item.)

In [14]:
X = np.array([[1,2,3],[4,5,6]])
y = np.ones((3,1))
(X.shape, y.shape)

((2, 3), (3, 1))

In [15]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
y

array([[1.],
       [1.],
       [1.]])

In [17]:
np.sum(y)

3.0

In [18]:
np.sum(X)

21

In [19]:
np.sum(X, axis=0)

array([5, 7, 9])

In [20]:
np.sum(X, axis=1)

array([ 6, 15])

In [21]:
np.mean(X)

3.5

In [22]:
np.mean(X, axis=0)

array([2.5, 3.5, 4.5])

In [23]:
np.mean(X, axis=1)

array([2., 5.])

In [24]:
np.mean(X[0,:])

2.0

In [25]:
np.mean(X[:,0])

2.5

__The End__