# Scikit-learn

![alt](http://www.scatter.com/images/DataLab_logo.jpg)

General documentation and examples for Scikit-learn are available at
- http://scikit-learn.org/stable/

__Relevant Libraries:__
- `Numpy` Adds Python support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.
- `SciPy` A collection of mathematical algorithms and convenience functions built on the `Numpy` extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data.
- `Pandas` Software library written for data manipulation and analysis in Python. Offers data structures and operations for manipulating numerical tables and time series.
- `Scikit-learn` A Python module for machine learning built on top of `SciPy` and distributed under the 3-Clause BSD license.

## Table of Contents
##### 1. Preprocessing
- Imputation, Scaling
- Feature Extraction

##### 2. Unsupervised Learning
- Dimensionality Reduction
- Clustering

##### 3. Supervised Learning
- Regression
- Classification

##### 4. Model Selection
- Cross Validation
- Grid Search

##### 5. Pipelines

In this tutorial we will use the `Boston` dataset, and the `Iris` dataset, both included with `sklearn`

In [0]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_boston
boston = load_boston()

from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [3]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

Convert the `.data` numpy arrays into pandas DataFrames for readability

In [0]:
boston_df = pd.DataFrame(boston.data, columns=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'])
boston_df['MEDV'] = boston.target

iris_df = pd.DataFrame(iris.data, columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width'])
iris_df['Species'] = iris.target

## 1. Preprocessing
http://scikit-learn.org/stable/modules/preprocessing.html#preprocessing

The preprocessing _transformations_ of Scikit-learn are classes with two methods:
1. `fit` which takes one or more columns of a numpy array or pandas dataframe and records some information about the data in those columns
1. `transform` which takes one or more columns of an array or dataframe (possibly the same as above, possibly different) and then returns a __numpy array__ based on the the _fitted_ data and the columns to _transform_

#### Imputation
Imputation replaces missing values with values based on the valid values in the row or column.

In [0]:
from sklearn.impute import SimpleImputer

In [9]:
X = np.array([[1,     np.nan], 
             [np.nan, 4], 
             [7,      6]
            ])
X

array([[ 1., nan],
       [nan,  4.],
       [ 7.,  6.]])

We must initialize the imputer object with specifications before we can fit and transfrom `X`. We will name it `imp`.

In [0]:
imp = SimpleImputer(strategy='mean')

Above we have specified the imputer to replace `'NaN'` with the `mean` of each column (`axis=0`).

Below, note fitting does not change `X`, it instead calculates the mean of each column and stores them in our object, `imp`.

In [15]:
imp.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [16]:
imp.statistics_

array([4., 5.])

The `transform` method creates, in this case, a new array with the missing values of `X` replaced with the mean of the column containing the missing value.

In [17]:
X_new = imp.transform(X)
X_new

array([[1., 5.],
       [4., 4.],
       [7., 6.]])

Our data sets do not have any missing values. Below we remove some values from the first column of our iris dataset to illustrate imputation.

In [18]:
iris_with_missing = iris_df[:].copy()
iris_with_missing.iloc[[3, 4, 12, 34, 47, 54, 59, 63, 105, 115], 0] = np.nan
iris_with_missing.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           NaN          3.1           1.5          0.2        0
4           NaN          3.6           1.4          0.2        0

In [19]:
iris_imp = SimpleImputer(strategy='mean', verbose=1)
iris_imp.fit(iris_with_missing)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=1)

In [20]:
iris_imp

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=1)

In [21]:
iris_with_missing

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             NaN          3.1           1.5          0.2        0
4             NaN          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [0]:
iris_filled = iris_imp.transform(iris_with_missing)

In [24]:
pd.DataFrame(iris_filled, columns = iris_df.columns)

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0        5.100000          3.5           1.4          0.2      0.0
1        4.900000          3.0           1.4          0.2      0.0
2        4.700000          3.2           1.3          0.2      0.0
3        5.862857          3.1           1.5          0.2      0.0
4        5.862857          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145      6.700000          3.0           5.2          2.3      2.0
146      6.300000          2.5           5.0          1.9      2.0
147      6.500000          3.0           5.2          2.0      2.0
148      6.200000          3.4           5.4          2.3      2.0
149      5.900000          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

Note that our dataframe is now a numpy array - we have lost our column headings and indices

__Exercise:__ Try changing the parameters in the examples above:
- strategy = `mean`, `median`, `most_frequent`
- axis = `0` (replace based on column), `1` (replace based on row)

In [25]:
iris_imp = SimpleImputer(strategy='median')
iris_imp.fit(iris_with_missing)
iris_imp.transform(iris_with_missing)

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [5.8, 3.1, 1.5, 0.2, 0. ],
       [5.8, 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [5.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

#### Scaling
Some machine learning methods assume that a column of data is in a specific range (for instance, 0 to 1) or that the data has a mean of 0 and a standard deviation of 1. Scalers transform the values of a dataframe to meet these assumptions. They are especially useful before applying distance-based models, where a variable with unusually large values can outweight the rest. 

Options:
- `MinMaxScaler` - Scales column data such that the minimum for each column is 0 and the maximum is 1
- `MaxAbsScaler` - Scales column data such that the maximum absolute value of each column is 1
- `StandardScaler` - Standardizes column data such that the mean of each column is 0 and the standard deviation of each is 1
- `Normalizer` - Scales __row__ data such that each row is a vector of length 1

In [0]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, Normalizer

__Exercise__: Compare each of the scalers below on `X` as well as our `iris_df`

In [27]:
X = np.array([[ 1., -1.,  2.],
              [ 100.,  0.,  0.],
              [ 0.,  1., -1.]])
X

array([[  1.,  -1.,   2.],
       [100.,   0.,   0.],
       [  0.,   1.,  -1.]])

In [28]:
scaler = MinMaxScaler()

scaler.fit(X)
scaler.transform(X)

array([[0.01      , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [29]:
iris_df.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [30]:
iris_measurements = iris_df.drop('Species', axis=1)
iris_measurements.describe()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [31]:
scaler_iris = MinMaxScaler()

scaler_iris.fit(iris_measurements)
iris_scaled = scaler_iris.transform(iris_measurements)
pd.DataFrame(iris_scaled, columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']).describe()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       0.428704     0.440556      0.467458     0.458056
std        0.230018     0.181611      0.299203     0.317599
min        0.000000     0.000000      0.000000     0.000000
25%        0.222222     0.333333      0.101695     0.083333
50%        0.416667     0.416667      0.567797     0.500000
75%        0.583333     0.541667      0.694915     0.708333
max        1.000000     1.000000      1.000000     1.000000

In [32]:
pd.DataFrame(iris_scaled, columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']).head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0      0.222222     0.625000      0.067797     0.041667
1      0.166667     0.416667      0.067797     0.041667
2      0.111111     0.500000      0.050847     0.041667
3      0.083333     0.458333      0.084746     0.041667
4      0.194444     0.666667      0.067797     0.041667

#### Feature Extraction
Feature extraction transforms variables so that they are more friendly to machine learning. Some examples include:
- Converting continuous variables to binary
- Converting categorical variables to binary dummy variables
- Converting raw sentences to word counts

In [0]:
from sklearn.preprocessing import Binarizer, LabelBinarizer, OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer

With `Binarizer` values above a given threshold become 1, and values equal-to or below the threshold become 0. We will demonstrate on our original array, `X`.

In [34]:
X

array([[  1.,  -1.,   2.],
       [100.,   0.,   0.],
       [  0.,   1.,  -1.]])

Below, instead of applying both `.fit()` and `.transform()`, we can instead equivalently use `.fit_transform()`

In [35]:
binarizer = Binarizer(threshold=0)

print(binarizer.fit(X).transform(X))
print('')
print(binarizer.fit_transform(X))

[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


`LabelBinarizer`
- Takes as input (to the `fit` method) a multi-class 1-dimensional feature (list of __strings__)
- Return as output (by the `transform` method) one or more binary features (numpy array)

`OneHotEncoder`
- Takes as input (to the `fit` method) a multi-class 1-dimensional feature (of categorical __integers__)
- Return as output (by the `transform` method) one or more binary features (numpy array)

In [36]:
lb = LabelBinarizer()
lb.fit(['A', 'B', 'A', 'C'])

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [37]:
lb.transform(['A', 'B', 'A', 'C'])

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

Above, `.fit()` determines that there are 3 unique values to be turned into binary columns.

Below, notice "D" is lost from our new vector because it was not part of our fit procedure.

In [38]:
lb.transform(['A', 'C', 'F'])

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

__Exercise:__ Create your own 1D array and apply `LabelBinarizer`.

In our `iris` dataset, our target variable `Species` is encoded as follows:
- Iris-Setosa (0)
- Iris-Versicolour (1)
- Iris-Virginica (2)

Using `OneHotEncoder`, we can convert this into three binary variables.

In [39]:
iris_df['Species'].value_counts()

2    50
1    50
0    50
Name: Species, dtype: int64

In [44]:
ohe = OneHotEncoder()
targets = ohe.fit_transform(iris_df[['Species']]) # .reshape(-1, 1) removes index from iris_df['Species]
targets.toarray() # Converts sparse matrix to array

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

`CountVectorizer`
- Takes as input (to the `fit` method) an array or list of __strings__
- Return as output (by the `transform` method) a sparse matrix of token counts, in alphabetical order of tokens. With default settings tokens are words, and the vectorizer removes punctuation and lowers the case.

In [0]:
documents = ['This is the first document.',
             'This is the second second document.',
             'And the third one.',
            ]

In [46]:
vectorizer = CountVectorizer()
vectorizer.fit(documents)
print(vectorizer.get_feature_names()) # Columns

matrix = vectorizer.transform(documents)
print(matrix.toarray()) # Counts

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]]


In [47]:
pd.DataFrame(matrix.toarray(), columns = vectorizer.get_feature_names())

and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         1      0   1    0       2    1      0     1
2    1         0      0   0    1       0    1      1     0

__Exercise:__ Write and vectorize your own sentences.

## 2. Unsupervised Learning

#### Dimensionality Reduction
The most common form of dimensionality reduction is `Principal Components Analysis`

Wikipedia: https://en.wikipedia.org/wiki/Principal_component_analysis
> Principal component analysis (PCA) is a statistical procedure that uses an orthogonal transformation to convert a set of observations of possibly correlated variables into a set of values of linearly uncorrelated variables called principal components.

In [0]:
from sklearn.decomposition import PCA

If we return to our `iris` dataset, some of our predictor variables are highly correlated. PCA can help with this.

In [49]:
iris_measurements.corr()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
Sepal_Length      1.000000    -0.117570      0.871754     0.817941
Sepal_Width      -0.117570     1.000000     -0.428440    -0.366126
Petal_Length      0.871754    -0.428440      1.000000     0.962865
Petal_Width       0.817941    -0.366126      0.962865     1.000000

Below, `.fit_transform()` returns a numpy array, which we convert again to a pandas DataFrame for readability.

In [50]:
iris_measurements.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [51]:
pca = PCA()
iris_pca = pca.fit_transform(iris_measurements) 
iris_pca = pd.DataFrame(iris_pca, columns=['PC1', 'PC2', 'PC3', 'PC4'])
iris_pca.head()

PC1       PC2       PC3       PC4
0 -2.684126  0.319397 -0.027915 -0.002262
1 -2.714142 -0.177001 -0.210464 -0.099027
2 -2.888991 -0.144949  0.017900 -0.019968
3 -2.745343 -0.318299  0.031559  0.075576
4 -2.728717  0.326755  0.090079  0.061259

Our 4 variables are now measured in terms of our 4 principal components. By default, we always return as many principal components as there are variables. Note our 4 principal components are completely uncorrelated.

In [52]:
np.round(iris_pca.corr(),2)

PC1  PC2  PC3  PC4
PC1  1.0  0.0  0.0  0.0
PC2  0.0  1.0  0.0  0.0
PC3  0.0  0.0  1.0  0.0
PC4  0.0  0.0  0.0  1.0

The other benefit of `PCA` is that the principal components are sorted in decreasing order of importance. Below, we can see that our first principal component explains __92%__ of the variation in our data, our second component explains __5%__, and the other two explain even less.

In [53]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261, 0.00521218])

The __Reduction__ part of Dimensionality Reduction comes from the fact that we can limit the number of principal components we want to keep in the returned dataset. We'll initialize the object `pca` to just use the first two, which explain almost 98% of the variation.

In [54]:
pca = PCA(n_components = 2)
iris_pca = pca.fit_transform(iris_measurements) 
iris_pca = pd.DataFrame(iris_pca, columns=['PC1', 'PC2'])
iris_pca.head()

PC1       PC2
0 -2.684126  0.319397
1 -2.714142 -0.177001
2 -2.888991 -0.144949
3 -2.745343 -0.318299
4 -2.728717  0.326755

__Exercise:__ Use PCA on the `boston_X` dataset below _(target variable `MEDV` removed)_. How many principal components would you keep?

In [55]:
boston_X = boston_df.drop('MEDV', axis=1)
boston_X.corr()

CRIM        ZN     INDUS  ...   PTRATIO         B     LSTAT
CRIM     1.000000 -0.200469  0.406583  ...  0.289946 -0.385064  0.455621
ZN      -0.200469  1.000000 -0.533828  ... -0.391679  0.175520 -0.412995
INDUS    0.406583 -0.533828  1.000000  ...  0.383248 -0.356977  0.603800
CHAS    -0.055892 -0.042697  0.062938  ... -0.121515  0.048788 -0.053929
NOX      0.420972 -0.516604  0.763651  ...  0.188933 -0.380051  0.590879
RM      -0.219247  0.311991 -0.391676  ... -0.355501  0.128069 -0.613808
AGE      0.352734 -0.569537  0.644779  ...  0.261515 -0.273534  0.602339
DIS     -0.379670  0.664408 -0.708027  ... -0.232471  0.291512 -0.496996
RAD      0.625505 -0.311948  0.595129  ...  0.464741 -0.444413  0.488676
TAX      0.582764 -0.314563  0.720760  ...  0.460853 -0.441808  0.543993
PTRATIO  0.289946 -0.391679  0.383248  ...  1.000000 -0.177383  0.374044
B       -0.385064  0.175520 -0.356977  ... -0.177383  1.000000 -0.366087
LSTAT    0.455621 -0.412995  0.603800  ...  0.374044 -0.366087  1.000000

[13 rows x 13 columns]

In [56]:
pca = PCA()
pca.fit(boston_X)
pca.explained_variance_ratio_.round(2)

array([0.81, 0.16, 0.02, 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  ])

In [57]:
pd.DataFrame(pca.components_[0].round(2).reshape(-1,13), columns=boston_X.columns)

CRIM    ZN  INDUS  CHAS  NOX   RM  ...   DIS   RAD   TAX  PTRATIO     B  LSTAT
0  0.03 -0.04   0.03  -0.0  0.0 -0.0  ... -0.01  0.05  0.95     0.01 -0.29   0.02

[1 rows x 13 columns]

In [58]:
pca = PCA(n_components = 2)
pca.fit_transform(boston_X)

array([[-119.81884272,   -5.56005586],
       [-168.89015548,   10.11620863],
       [-169.31170747,   14.0805323 ],
       ...,
       [-138.38716306,    0.9380922 ],
       [-137.50517338,    4.2518251 ],
       [-139.19033295,    1.00906423]])

#### Clustering
Clustering groups similar data points into sets. There are many variants. We will focus on `K-Means`.

Wikipedia: https://en.wikipedia.org/wiki/K-means_clustering
> K-means clustering aims to partition n observations into k clusters in which each observation belongs to the cluster with the nearest mean, serving as a prototype of the cluster

In [0]:
from sklearn.cluster import KMeans

We will use our `iris_scaled` array from earlier. Because `KMeans` is distance based, it would be biased to separate clusters along features with different scales.

From the documentation, we know these plants belong to three species. Lets try to create three clusters and see how they compare to the real groupings. As a reminder, the first 5 rows of our scaled array are printed below.

In [60]:
iris_scaled[0:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

Below, we first specify a `random_state`. There is some randomness involved in identifying clusters, so this enables reproducibility. The `.fit()` method divides the data into clusters, and calculates the centers of each cluster. The `.predict()` method then labels data points according to the cluster centers calculated earlier.

In [0]:
km = KMeans(n_clusters=3, random_state=1)
km.fit(iris_scaled)
clusters = km.predict(iris_scaled)

In [62]:
pd.crosstab(clusters, iris_df['Species'])

Species   0   1   2
row_0              
0         0   3  36
1        50   0   0
2         0  47  14

Not too bad! The cluster numbers are meaningless, but we can see that species 0 (column) is completely identified in a cluster, species 1 (column) is almost completely identified in a cluster, and species 2 is split between two clusters.

## 3. Supervised Learning

The supervised learning _estimators_ of Scikit-learn are classes with two methods:
1. `fit` which takes a numpy array or pandas dataframe of predictor variables as well as a 1D array or dataframe for the target variable
1. `predict` which takes a numpy array or pandas dataframe with the same columns as the predictor variables and returns a __numpy array__ of estimates based on the the _fitted_ data

_Important note: all data must be numeric (or transformed to numeric from categories or labels above)_

#### Regression
Predicting a continuous-valued attribute. We will use our `Boston` dataset, to predict `MEDV` (Median Home Value) based on the other predictors. Let's first split our data into training and test sets, so we can evaluate how well it predicts for unseen data.

_Note: `train_test_split` converts our data into numpy arrays_

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(boston_df.drop('MEDV', axis=1),
                                                    boston_df['MEDV'],
                                                    test_size = 0.33, random_state=1
                                                   )

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339,), (167,))

In this example we will use a simple `LinearRegression` model, and look at `Mean Squared Error` and `R-squared` to assess our predictions. We `.fit()` our model to the training data, `.predict()` based on the test data, and score the true y-values against our predictions.

In [64]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

lm = LinearRegression()
lm.fit(X_train, y_train)

y_pred = lm.predict(X_test)

print('MSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

MSE: 20.698475744484185
R2: 0.7649416667641552


__Exercise:__ Use a linear regression to predict `CRIM` (crime rate) based on all other predictors. Make sure to split the data into training and test sets.

In [65]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

#### Classification
Identifying to which category an object belongs to. We will use our __scaled__ `Iris` dataset to predict species using a `LogisticRegression` and evaluate the `accuracy score` (percent correct classes). Again we will split our data into training and test sets, `.fit()` to the training set, `.predict()` based on the test set, and score those predictions against the true categories.

In [0]:
X_train, X_test, y_train, y_test = train_test_split(iris_scaled,
                                                    iris_df['Species'],
                                                    test_size = 0.33, random_state=1
                                                   )

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

logfit = LogisticRegression(multi_class='multinomial', solver='newton-cg')
logfit.fit(X_train, y_train)

y_pred = logfit.predict(X_test)
print(pd.crosstab(y_pred, y_test))

print('')
print('accuracy:', accuracy_score(y_test, y_pred))

Species   0   1   2
row_0              
0        17   0   0
1         0  16   1
2         0   3  13

accuracy: 0.92


We can also extract the predicted probabilities for each class. The prediction above is based on the class with the highest probability. 

Below, we print the first 5 rows of these predicted probabilities.

In [68]:
y_probs = logfit.predict_proba(X_test)
y_probs[0:5]

array([[0.89290474, 0.09330937, 0.0137859 ],
       [0.3062854 , 0.5508175 , 0.14289711],
       [0.08998606, 0.47637565, 0.4336383 ],
       [0.87764167, 0.10409289, 0.01826544],
       [0.00753157, 0.13084507, 0.86162336]])

For a complete list of classification and regression models, see http://scikit-learn.org/stable/supervised_learning.html#supervised-learning

## 4. Model Selection

To avoid overfitting, earlier we split our data into training and test sets, and only scored the model based on the test set. While this is a good process for understanding our final model's predictive power, if we leverage the test data too early in our process we risk overfitting by model choice. 

For this reason, the best process is to do all of our fitting, model selection, and parameter tuning on _only the training data_, and to not use the test data until we have chosen our model and parameters. Only then does our test data gives us a true score.

#### Cross Validation
Cross validation is the process of dividing data into equal subsets, and using each subset for scoring a model fit on all other subsets.
Wikipedia: https://en.wikipedia.org/wiki/Cross-validation_(statistics)

![alt](https://upload.wikimedia.org/wikipedia/commons/1/1c/K-fold_cross_validation_EN.jpg)

In scikit-learn, `cross_val_score` implements this process for a variety of metrics 
- Documentation: http://scikit-learn.org/stable/modules/cross_validation.html
- List of metrics: http://scikit-learn.org/stable/modules/model_evaluation.html

Below, we will use cross validation on our training data from the Iris classification problem earlier. By setting `cv=5`, we divide our data into 5 folds.

In [69]:
from sklearn.model_selection import cross_val_score

logfit = LogisticRegression(multi_class='multinomial', solver='newton-cg')
scores = cross_val_score(logfit, 
                         X_train, 
                         y_train, 
                         scoring='accuracy', 
                         cv=5)

print(scores)
print(scores.mean())

[0.9  0.95 0.9  0.95 0.85]
0.9099999999999999


__Exercise:__ Pick a different metric and score the training data.

#### Grid Search
If our model has parameters we can tune, `GridSearchCV` can help. It implements the cross-validation process above, but calculates scores for a grid of possible input parameters. We can then use the best scoring model to make predictions.

In [0]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

For this example, we will use `KNeighborsClassifier`, which is a supervised learning method that labels data points according to the most common class among its  `K` closest data points. For small values of `K`, the model draws a jagged boundary that is more susceptible to noise but can also fit nonlinear patterns. For larger values of `K`, the boundary between classes is smoothed. We will use `GridSearchCV` to find the ideal value of `K`.

In [0]:
parameters = {'n_neighbors': [1, 5, 7, 11, 13],
              'weights': ['uniform', 'distance']
             }

knn = KNeighborsClassifier()
grid = GridSearchCV(estimator=knn,
                    param_grid = parameters,
                    scoring = 'accuracy',
                    cv = 3
                   )

Notes on our parameters above:
- For `n_neighbors`, because we have 3 classes and want to avoid ties, we do not use even numbers or numbers divisible by 3
- For weights, `'uniform'` gives all points equal weight, `'distance'` gives more weight to closer points

Below, we fit our grid object to the scaled training data.

In [72]:
grid.fit(X_train, y_train)

print('Best Accuracy Score:', grid.best_score_)
print('Best Parameters:', grid.best_params_)

Best Accuracy Score: 0.9699940582293524
Best Parameters: {'n_neighbors': 5, 'weights': 'uniform'}


The best-scoring model fits to the __5__ nearest neighbors, and gives each neighbor an equal weight. We can also make predictions using the grid object - it uses the best model. This was our best model and best parameters above, we could now bring back the test data.

In [73]:
y_pred = grid.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))

Accuracy: 0.96


__Exercise:__ Make some changes to the parameter grid, and change the scoring metric. Are there any changes to the best model?

## 5. Pipelines

There are a lot of steps above to transform data in the way we want. Luckily, we can combine all of our transformers and an estimator into a pipeline object to speed up the process. Let's return to our messy iris data from earlier (`iris_with_missing`), and split that into training and test data.

In [0]:
from sklearn.pipeline import Pipeline

In [75]:
iris_with_missing.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           NaN          3.1           1.5          0.2        0
4           NaN          3.6           1.4          0.2        0

In [0]:
X_train, X_test, y_train, y_test = train_test_split(iris_with_missing.drop('Species', axis=1),
                                                    iris_with_missing['Species'],
                                                    test_size = 0.33, random_state=1
                                                   )

A `Pipeline` object takes as input a list of tuples where each tuple has: 
- A name (`string`)
- A transformer object 

The objects run in sequence, and the last item in a `Pipeline` is typically an estimator object. Below we use an `Imputer`, `MinMaxScaler`, `PCA`, and our `KNeighborsClassifier` estimator.

In [0]:
Pipe = Pipeline([('imputer', SimpleImputer(strategy='mean')),
                 ('scaler' , MinMaxScaler()),
                 ('pca'    , PCA()),
                 ('knn'    , KNeighborsClassifier(weights='uniform'))
                 ])

Notice we haven't done anything with our data yet. We will now fit the pipeline to the training data, use `GridSearchCV` to select the best parameters, and finally make predictions on the test data. The pipeline will transform the test data exactly in the way it transforms the training data.

To use a grid search with a pipeline, we must identify the step name from above, followed by two underscores, followed by the parameter name

In [0]:
parameters = {'pca__n_components': [1, 2, 3, 4],
              'knn__n_neighbors': [5, 7, 11]
             }

grid = GridSearchCV(estimator=Pipe,
                    param_grid = parameters,
                    scoring = 'accuracy',
                    cv = 3
                   )

In [80]:
grid.fit(X_train, y_train)

print('Best Accuracy Score:', grid.best_score_)
print('Best Parameters:', grid.best_params_)

Best Accuracy Score: 0.9699940582293524
Best Parameters: {'knn__n_neighbors': 5, 'pca__n_components': 4}


In [81]:
y_pred = grid.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))

Accuracy: 0.96


__Exercise:__ Create and fit a pipeline to the `Boston` dataset. The pipeline should include a `scaler`, `PCA`, and `LinearRegression`. Use `GridSearchCV` to determine the best number of PCA components to include (based on `Mean Squared Error`).

What is the `Mean Squared Error` of final predictions on the test data?

In [82]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

__The End__